# Generated by Django 3.2.5 on 2021-07-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0002_imageslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/%y')),
                ('caption', models.CharField(max_length=100)),
            ],
        ),
    ]
