# Generated by Django 3.2.5 on 2021-07-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0003_ceoimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CeoImage',
        ),
        migrations.AddField(
            model_name='image',
            name='BackdroundImage',
            field=models.ImageField(default=0, upload_to='img/%y'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='ceoimage',
            field=models.ImageField(default=0, upload_to='img/%y'),
            preserve_default=False,
        ),
    ]
