# Generated by Django 3.2.5 on 2021-07-15 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0004_auto_20210715_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='BackdroundImage',
        ),
        migrations.RemoveField(
            model_name='image',
            name='ceoimage',
        ),
    ]
